version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    image: borismanev/marketscraper_web:latest
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  ofelia:
    image: mcuadros/ofelia:latest
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
    labels:
      ofelia.job-run.scrape_it_mk.schedule: "0 32 2 * * *"
      ofelia.job-run.scrape_it_mk.image: "borismanev/it_mk_scraper:latest"
      ofelia.job-run.scrape_it_mk.command: "/usr/local/bin/python /app/it_mk_scraper.py"
      ofelia.job-run.scrape_it_mk.network: "marketscraper_default"
      ofelia.job-run.scrape_it_mk.overlapping: "false"
      ofelia.job-run.scrape_it_mk.max_running: "1"
      ofelia.job-run.scrape_it_mk.remove: "true"
      ofelia.job-run.scrape_it_mk.environment: >-
        ["POSTGRES_HOST=db",
         "POSTGRES_DB=${POSTGRES_DB}",
         "POSTGRES_USER=${POSTGRES_USER}",
         "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}",
         "START_PAGE=1",
         "END_PAGE=2",
         "BATCH_SIZE=1"]

      ofelia.job-run.scrape_pazar3.schedule: "0 25 2 * * *"
      ofelia.job-run.scrape_pazar3.image: "borismanev/pazar3_scraper:latest"
      ofelia.job-run.scrape_pazar3.command: "/usr/local/bin/python /app/pazar3_scraper.py"
      ofelia.job-run.scrape_pazar3.network: "marketscraper_default"
      ofelia.job-run.scrape_pazar3.overlapping: "false"
      ofelia.job-run.scrape_pazar3.max_running: "1"
      ofelia.job-run.scrap_pazar3.remove: "true"
      ofelia.job-run.scrape_pazar3.environment: >-
        ["POSTGRES_HOST=db",
         "POSTGRES_DB=${POSTGRES_DB}",
         "POSTGRES_USER=${POSTGRES_USER}",
         "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}",
         "START_PAGE=1",
         "END_PAGE=5",
         "BATCH_SIZE=3"]

      ofelia.job-run.scrape_rk5.schedule: "0 28 2 * * *"
      ofelia.job-run.scrape_rk5.image: "borismanev/reklama5_scraper:latest"
      ofelia.job-run.scrape_rk5.command: "/usr/local/bin/python /app/rk5_scraper.py"
      ofelia.job-run.scrape_rk5.network: "marketscraper_default"
      ofelia.job-run.scrape_rk5.overlapping: "false"
      ofelia.job-run.scrape_rk5.max_running: "1"
      ofelia.job-run.scrape_rk5.remove: "true"
      ofelia.job-run.scrape_rk5.environment: >-
        ["POSTGRES_HOST=db",
         "POSTGRES_DB=${POSTGRES_DB}",
         "POSTGRES_USER=${POSTGRES_USER}",
         "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}",
         "START_PAGE=1",
         "END_PAGE=5",
         "BATCH_SIZE=3"]

volumes:
  postgres_data:
