version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    image: borismanev/marketscraper_web:latest
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  ofelia:
    image: mcuadros/ofelia:latest
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
    labels:
      # IT MK Scraper job-run
      ofelia.job-run.scrape_it_mk.schedule: "20 4 * * *"
      ofelia.job-run.scrape_it_mk.image: "borismanev/it_mk_scraper:latest"
      ofelia.job-run.scrape_it_mk.command: "/usr/local/bin/python /app/it_mk_scraper.py"
      ofelia.job-run.scrape_it_mk.env.DB_HOST: "db"
      ofelia.job-run.scrape_it_mk.env.DB_NAME: "${POSTGRES_DB}"
      ofelia.job-run.scrape_it_mk.env.DB_USER: "${POSTGRES_USER}"
      ofelia.job-run.scrape_it_mk.env.DB_PASSWORD: "${POSTGRES_PASSWORD}"
      ofelia.job-run.scrape_it_mk.env.START_PAGE: "1"
      ofelia.job-run.scrape_it_mk.env.END_PAGE: "2"
      ofelia.job-run.scrape_it_mk.env.BATCH_SIZE: "1"

      # Pazar3 Scraper job-run
      ofelia.job-run.scrape_pazar3.schedule: "25 4 * * *"
      ofelia.job-run.scrape_pazar3.image: "borismanev/pazar3_scraper:latest"
      ofelia.job-run.scrape_pazar3.command: "/usr/local/bin/python /app/pazar3_scraper.py"
      ofelia.job-run.scrape_pazar3.env.DB_HOST: "db"
      ofelia.job-run.scrape_pazar3.env.DB_NAME: "${POSTGRES_DB}"
      ofelia.job-run.scrape_pazar3.env.DB_USER: "${POSTGRES_USER}"
      ofelia.job-run.scrape_pazar3.env.DB_PASSWORD: "${POSTGRES_PASSWORD}"
      ofelia.job-run.scrape_pazar3.env.START_PAGE: "1"
      ofelia.job-run.scrape_pazar3.env.END_PAGE: "5"
      ofelia.job-run.scrape_pazar3.env.BATCH_SIZE: "3"

      # Reklama5 Scraper job-run
      ofelia.job-run.scrape_rk5.schedule: "30 4 * * *"
      ofelia.job-run.scrape_rk5.image: "borismanev/reklama5_scraper:latest"
      ofelia.job-run.scrape_rk5.command: "/usr/local/bin/python /app/rk5_scraper.py"
      ofelia.job-run.scrape_rk5.env.DB_HOST: "db"
      ofelia.job-run.scrape_rk5.env.DB_NAME: "${POSTGRES_DB}"
      ofelia.job-run.scrape_rk5.env.DB_USER: "${POSTGRES_USER}"
      ofelia.job-run.scrape_rk5.env.DB_PASSWORD: "${POSTGRES_PASSWORD}"
      ofelia.job-run.scrape_rk5.env.START_PAGE: "1"
      ofelia.job-run.scrape_rk5.env.END_PAGE: "5"
      ofelia.job-run.scrape_rk5.env.BATCH_SIZE: "3"

volumes:
  postgres_data:
