version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ./Web
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  it_mk_scraper:
    build:
      context: ./scrapers/it_mk_scraper
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      START_PAGE: 1
      END_PAGE: 2
      BATCH_SIZE: 1
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.scrape_it_mk.schedule: "20 4 * * *"
      ofelia.job-exec.scrape_it_mk.command: "/usr/local/bin/python /app/it_mk_scraper.py"

  pazar3_scraper:
    build:
      context: ./scrapers/pazar3_scraper
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      START_PAGE: 1
      END_PAGE: 5
      BATCH_SIZE: 3
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.scrape_pazar3.schedule: "25 4 * * *"
      ofelia.job-exec.scrape_pazar3.command: "/usr/local/bin/python /app/pazar3_scraper.py"

  rk5_scraper:
    build:
      context: ./scrapers/reklama5_scraper
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      START_PAGE: 1
      END_PAGE: 5
      BATCH_SIZE: 3
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.scrape_rk5.schedule: "30 4 * * *"
      ofelia.job-exec.scrape_rk5.command: "/usr/local/bin/python /app/rk5_scraper.py"

  ofelia:
    image: mcuadros/ofelia:latest
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - it_mk_scraper
      - pazar3_scraper
      - rk5_scraper

volumes:
  postgres_data:
